// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdFYb_QfE2aoY5xVniG5BxUNBqCjmqJfM',
    appId: '1:798534355553:web:03504a1b9d6ff436a57820',
    messagingSenderId: '798534355553',
    projectId: 'edumaappnew',
    authDomain: 'edumaappnew.firebaseapp.com',
    storageBucket: 'edumaappnew.firebasestorage.app',
    measurementId: 'G-QLHH7F61XS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNasxF3h_cCXJtzIsvWL8dppgaqjl8btw',
    appId: '1:798534355553:android:048da4e68ed52d5ca57820',
    messagingSenderId: '798534355553',
    projectId: 'edumaappnew',
    storageBucket: 'edumaappnew.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcilx9Aic3i1xrhEZoRXdCwPbGu334_QY',
    appId: '1:798534355553:ios:932d2f7479409eb5a57820',
    messagingSenderId: '798534355553',
    projectId: 'edumaappnew',
    storageBucket: 'edumaappnew.firebasestorage.app',
    androidClientId: '798534355553-pr5a7ag85kumfrfnmdvi30qi0nir8fuj.apps.googleusercontent.com',
    iosClientId: '798534355553-njdab13bu0muvvvi46dv7b7280cnkqqn.apps.googleusercontent.com',
    iosBundleId: 'com.example.newEducationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcilx9Aic3i1xrhEZoRXdCwPbGu334_QY',
    appId: '1:798534355553:ios:932d2f7479409eb5a57820',
    messagingSenderId: '798534355553',
    projectId: 'edumaappnew',
    storageBucket: 'edumaappnew.firebasestorage.app',
    androidClientId: '798534355553-pr5a7ag85kumfrfnmdvi30qi0nir8fuj.apps.googleusercontent.com',
    iosClientId: '798534355553-njdab13bu0muvvvi46dv7b7280cnkqqn.apps.googleusercontent.com',
    iosBundleId: 'com.example.newEducationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdFYb_QfE2aoY5xVniG5BxUNBqCjmqJfM',
    appId: '1:798534355553:web:27b036834c997e27a57820',
    messagingSenderId: '798534355553',
    projectId: 'edumaappnew',
    authDomain: 'edumaappnew.firebaseapp.com',
    storageBucket: 'edumaappnew.firebasestorage.app',
    measurementId: 'G-X0KE4RJN7V',
  );
}
